# Netlify Configuration File

[build]
  base = "frontend"  # Path to frontend folder
  publish = "frontend/build"  # Folder to deploy after build
  command = "npm install && npm run build"  # Install dependencies & build project

[context.production.environment]
  REACT_APP_API_KEY = "your-api-key-here"
  REACT_APP_AUTH_DOMAIN = "your-auth-domain"
  REACT_APP_PROJECT_ID = "your-project-id"
  REACT_APP_STORAGE_BUCKET = "your-storage-bucket"
  REACT_APP_MESSAGING_SENDER_ID = "your-messaging-sender-id"
  REACT_APP_APP_ID = "your-app-id"
  REACT_APP_MEASUREMENT_ID = "your-measurement-id"

# Run tests before deploying (optional)
[build.lifecycle]
  onBuild = "npm test"  # Ensures tests pass before deploying
