# Netlify Configuration File Working

[build]
  base = "frontend"  
  publish = "build"  
  command = "npm install && npm run build"  

[build.environment]
  NODE_VERSION = "20"

# Remove/comment out the production environment section since we're using UI variables
# [context.production.environment]
#   REACT_APP_API_KEY = "your-api-key-here"
#   REACT_APP_AUTH_DOMAIN = "your-auth-domain"
#   REACT_APP_PROJECT_ID = "your-project-id"
#   REACT_APP_STORAGE_BUCKET = "your-storage-bucket"
#   REACT_APP_MESSAGING_SENDER_ID = "your-messaging-sender-id"
#   REACT_APP_APP_ID = "your-app-id"
#   REACT_APP_MEASUREMENT_ID = "your-measurement-id"



# Run tests before deploying (optional)
[build.lifecycle]
  onBuild = "npm test"