# Netlify Configuration File Working

[build]
  base = "frontend"  
  publish = "build"  
  command = "npm install && npm run build"  

[build.environment]
  NODE_VERSION = "20"

# Run tests before deploying (optional)
[build.lifecycle]
  onBuild = "npm test"